### PR TITLE
cats 1.0.0-MF

### PR DESCRIPTION
**Pull request by tpolecat**
It would be nice to get a milestone out at some point.

### CODE REVIEW

**Comment by tpolecat** [comment]
Hey I'm a maintainer. I'll be damned.

**Comment by tpolecat** [comment]
Hm looks like CI is trying to build JS but it's not actually set up in `build.sbt`.

**Comment by anicolaspp** [comment]
What is going on with @stew? Where is he?

**Comment by tpolecat** [comment]
I'm trying to get scala-js working. PR coming.

**Comment by tpolecat** [comment]
ok attempted to fix the build … it's tied up with the mods here because I needed `Is` to get rid of a compiler warning

**Comment by tpolecat** [comment]
son of bitch. i think it's good but something in the build is randomly hanging

**Comment by tpolecat** [comment]
Ok at long last this builds. @stew could you take a look? Due to build changes I think this needs to go to the head of the line. I recommend a squash commit because there's a bunch of bullshit in the history.

**Pull request closed without merging**
